version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: kanboard_app
    ports:
      - 8890:8890
    volumes:
      - ./:/var/www
    depends_on:
      - db
    networks:
      - kanboard

  db:
    image: mysql:8.0
    container_name: kanboard_db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: kanboard
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: kanboard_user
      MYSQL_PASSWORD: kanboard_password
    ports:
      - 3306:3306
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - kanboard

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: kanboard_phpmyadmin
    restart: unless-stopped
    ports:
      - 8080:80
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: root
    depends_on:
      - db
    networks:
      - kanboard

networks:
  kanboard:

volumes:
  db_data:
