services:
  app:
    build:
      context: .
      dockerfile: dockerfile
    volumes:
      - .:/var/www
    depends_on:
      - db

  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: kanboard
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - db_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - "8080:80"
    environment:
      PMA_HOST: db
      PMA_PORT: 3306

  nginx:
    image: nginx:1.27
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/conf/kanboard-ssl.conf:/etc/nginx/conf.d/default.conf
      - ./public:/var/www/public
      - ./nginx/conf/mykanplan.fr.crt:/etc/nginx/ssl/mykanplan.fr.crt
      - ./nginx/conf/mykanplan.fr.key:/etc/nginx/ssl/mykanplan.fr.key
    depends_on:
      - app

volumes:
  db_data:
